baseURL = "https://modest-mirzakhani-9fdfb6.netlify.com/"
languageCode = "ro-ro"
title = "Stonks.ro"
copyright = "Copyright &copy; 2020 - Robert"
canonifyurls = true
theme = "kiera"

paginate = 3

summaryLength = 30
enableEmoji = true


[author]
    name = "Robert"     #Author name
    twitter = ""        #Twitter username

[params]
    tagline = "GÃ¢nduri. Analize. Stonks."
    customCSS = []  #Optional Customised CSS
    disableDarkModeCSS = false # disables css style for users using dark-mode